// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOnxA86zGGDbrhwB5Eu4oS_WPDUnYRs5s',
    appId: '1:727974995113:android:6a864468378c85c1b1b5b8',
    messagingSenderId: '727974995113',
    projectId: 'aadhaar-nsp-2026',
    storageBucket: 'aadhaar-nsp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_-hO7Ye5GioAVv3YD_7LOv1GYZ29nznI',
    appId: '1:727974995113:ios:9a5e09d276a68900b1b5b8',
    messagingSenderId: '727974995113',
    projectId: 'aadhaar-nsp-2026',
    storageBucket: 'aadhaar-nsp-2026.firebasestorage.app',
    iosBundleId: 'com.starwish.adhaar',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbwuSvfvDI26_6OnZ6hGv3UCGRKdgVlC0',
    appId: '1:727974995113:web:51229e56b1808f52b1b5b8',
    messagingSenderId: '727974995113',
    projectId: 'aadhaar-nsp-2026',
    authDomain: 'aadhaar-nsp-2026.firebaseapp.com',
    storageBucket: 'aadhaar-nsp-2026.firebasestorage.app',
    measurementId: 'G-JE5JD6YHZH',
  );

}